import type { Metadata } from 'next';
import './globals.css';
import Providers from '@/components/Providers/Providers';
import '@/styles/fonts.css';
import { Toaster } from 'sonner';

export const metadata: Metadata = {
  title: 'Brain Flip',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light" data-theme="light">
      <body>
        <div
          id="header-portal"
          className="fixed top-0 left-0 right-0 h-14 lg:h-16 z-50"
        ></div>
        <Toaster richColors position="top-center" />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
