import type { Metadata } from 'next';
import { Header } from '@/components/Header/Header';

export const metadata: Metadata = {
  title: 'Brain Flip',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="pt-14 lg:pt-16 main-container min-h-screen dark:bg-main-dark">
      <Header />
      {children}
    </main>
  );
}
